lib/c_portfolio_web/router.ex
defmodule CPortfolioWeb.Router do
  use CPortfolioWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", CPortfolioWeb do
    pipe_through :browser
     
    get "/", PageController, :index
    get "/about", AboutController, :index
    get "/contact", ContactController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", CPortfolioWeb do
  #   pipe_through :api
  # end
end

lib/c_portfolio/application.ex
defmodule CPortfolio.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    # List all child processes to be supervised
    children = [
      # Start the Ecto repository
      CPortfolio.Repo,
      # Start the endpoint when the application starts
      CPortfolioWeb.Endpoint
      # Starts a worker by calling: CPortfolio.Worker.start_link(arg)
      # {CPortfolio.Worker, arg},
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: CPortfolio.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    CPortfolioWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/c_portfolio/repo.ex
defmodule CPortfolio.Repo do
  use Ecto.Repo,
    otp_app: :c_portfolio,
    adapter: Ecto.Adapters.Postgres
end

lib/c_portfolio_web/controllers/contactpage_controller.ex
defmodule CPortfolioWeb.ContactController do
  use CPortfolioWeb, :controller
   def index(conn, _params) do
   	render(conn, "index.html")
   end
	
end

lib/c_portfolio_web/controllers/page_controller.ex
defmodule CPortfolioWeb.PageController do
  use CPortfolioWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

lib/c_portfolio_web/views/about_view.ex
defmodule CPortfolioWeb.AboutView do
	use CPortfolioWeb, :view
	
end

lib/c_portfolio_web/views/contact_view.ex
defmodule CPortfolioWeb.ContactView do
	use CPortfolioWeb, :view
	
end

lib/c_portfolio_web/views/error_view.ex
defmodule CPortfolioWeb.ErrorView do
  use CPortfolioWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/c_portfolio_web/views/layout_view.ex
defmodule CPortfolioWeb.LayoutView do
  use CPortfolioWeb, :view
end

lib/c_portfolio_web/views/page_view.ex
defmodule CPortfolioWeb.PageView do
  use CPortfolioWeb, :view
end

lib/c_portfolio_web/templates/about/index.html.eex
<div class>
  <h1><%= gettext "Welcome to %{name}", name: "My portfolio" %></h1>
  <p>Vibrant Village is a private foundation working to improve food security, family health, financial wellbeing, and education in communities around the world. We make grants to non-profit organizations and directly manage programs from our field offices in Ecuador, Ghana, and Kenya.</p>
  </div>

lib/c_portfolio_web/templates/contact/index.html.eex
<section class="phx-hero">
  <h1><%= gettext "Welcome to %{name}!", name: "My Portfolio" %></h1>
  <p>Female Activist<br/>Mathematics And Computer Science Student</p>
</section>

lib/c_portfolio_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>CYNTHIA OTIENO</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <%= csrf_meta_tag() %>
  </head>
  <body>
    <%= render "navigation.html", conn: @conn %>
    <main role="main">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/c_portfolio_web/templates/layout/navigation.html.eex
<nav class="flex items-center justify-between flex-wrap bg-grey-lighter p-3 font-sans">
  <div class="flex items-center flex-no-shrink text-grey-darkest mr-6">
    <span class="font-semibold text-xl tracking-tight">Cynthia Otieno</span>
  </div>
  <div class="block lg:hidden">
    <button class="flex items-center px-3 py-2 border rounded text-grey-darkest border-grey-darkest" onclick="navbarAccordian()">
      <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
    </button>
  </div>
  <div class="hidden w-full block flex-grow lg:flex lg:items-center lg:w-auto" id="nav">
    <div class="text-sm lg:flex-grow">
    </div>
    <div>
      <a href="#" class="block mt-4 lg:inline-block lg:mt-0 text-grey-darkest mr-4 no-underline hover:underline">
        <%= link "Home", to: Routes.page_path(@conn, :index) %>
      </a>
      <a href="#" class="block mt-4 lg:inline-block lg:mt-0 text-grey-darkest mr-4 no-underline hover:underline">
        <%= link "About", to: Routes.about_path(@conn, :index) %>
      </a>
      <a href="#" class="block mt-4 lg:inline-block lg:mt-0 text-grey-darkest mr-4 no-underline hover:underline">
        <%= link "Contact", to: Routes.contact_path(@conn, :index) %>
      </a>
    </div>
  </div>
  <script>
    function navbarAccordian() {
    var x = document.getElementById("nav");
    x.classList.toggle("hidden");
    }
  </script>
</nav>

lib/c_portfolio_web/templates/page/index.html.eex
<section class="phx-hero">
  <h1><%= gettext "Welcome to %{name}!", name: "My Portfolio" %></h1>
  <p>Female Activist<br/>Mathematics And Computer Science Student</p>
</section>